"""modifiation of user model

Revision ID: 09eab305b50b
Revises: 49d4784ed472
Create Date: 2025-11-06 16:00:29.802408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09eab305b50b'
down_revision: Union[str, None] = '49d4784ed472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_avatar', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('dial_code', sa.String(), nullable=True))
    op.drop_column('users', 'profile_avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_avatar_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('users', 'dial_code')
    op.drop_column('users', 'profile_avatar')
    # ### end Alembic commands ###
