"""modification of Property model

Revision ID: 09ec07304e87
Revises: 9e6310744cc4
Create Date: 2025-09-24 11:20:06.180436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ec07304e87'
down_revision: Union[str, None] = '9e6310744cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_image_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('secure_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_cloud_image_details_id'), 'cloud_image_details', ['id'], unique=False)
    op.add_column('properties', sa.Column('type', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('cover_image_id', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('other_images_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_properties_other_images_id_cloud_image_details', 'properties', 'cloud_image_details', ['other_images_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_properties_cover_image_id_cloud_image_details', 'properties', 'cloud_image_details', ['cover_image_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('properties', 'has_features')
    op.drop_column('properties', 'lease_duration')
    op.drop_column('properties', 'category')
    op.drop_column('properties', 'status')
    op.drop_column('properties', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('lease_duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('has_features', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_properties_cover_image_id_cloud_image_details', 'properties', type_='foreignkey')
    op.drop_constraint('fk_properties_other_images_id_cloud_image_details', 'properties', type_='foreignkey')
    op.drop_column('properties', 'other_images_id')
    op.drop_column('properties', 'cover_image_id')
    op.drop_column('properties', 'type')
    op.drop_index(op.f('ix_cloud_image_details_id'), table_name='cloud_image_details')
    op.drop_table('cloud_image_details')
    # ### end Alembic commands ###
