"""modification of cover_image_id nullable of properties table to true

Revision ID: 0da79bed1940
Revises: 7cb47fb94966
Create Date: 2025-09-25 00:37:07.598940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da79bed1940'
down_revision: Union[str, None] = '7cb47fb94966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'cover_image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'cover_image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
