"""modification of Transaction model

Revision ID: 1021738fe51d
Revises: a30ff7e5a64c
Create Date: 2025-11-03 00:58:39.734558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1021738fe51d'
down_revision: Union[str, None] = 'a30ff7e5a64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('name', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('trx_type', sa.Enum('deposit', 'withdraw', name='transaction_type'), nullable=False))
    op.add_column('transactions', sa.Column('trx_id', sa.String(), nullable=True))
    op.alter_column('transactions', 'investment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', postgresql.ENUM('deposit', 'withdraw', name='transaction_type'), autoincrement=False, nullable=False))
    op.alter_column('transactions', 'investment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'trx_id')
    op.drop_column('transactions', 'trx_type')
    op.drop_column('transactions', 'name')
    # ### end Alembic commands ###
