"""Modification of Booking model

Revision ID: 157d5c6ca2b2
Revises: 09eab305b50b
Create Date: 2025-11-21 06:41:10.082101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '157d5c6ca2b2'
down_revision: Union[str, None] = '09eab305b50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guest_name', sa.String(length=255), nullable=False))
    op.add_column('bookings', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('bookings', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('price_per_night', sa.Float(), nullable=False))
    op.add_column('bookings', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('bookings', sa.Column('paid_amount', sa.Float(), nullable=False))
    op.add_column('bookings', sa.Column('balance_payment', sa.Float(), nullable=False))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('total_number_of_days', sa.Integer(), nullable=False))
    op.alter_column('bookings', 'check_in',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index('ix_bookings_room_check_in_check_out', 'bookings', ['room_id', 'check_in', 'check_out'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_foreign_key('fk_bookings_hotels', 'bookings', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_hotels', 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index('ix_bookings_room_check_in_check_out', table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id'), table_name='bookings')
    op.alter_column('bookings', 'check_in',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('bookings', 'total_number_of_days')
    op.drop_column('bookings', 'hotel_id')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'balance_payment')
    op.drop_column('bookings', 'paid_amount')
    op.drop_column('bookings', 'total_amount')
    op.drop_column('bookings', 'price_per_night')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'phone')
    op.drop_column('bookings', 'guest_name')
    # ### end Alembic commands ###
