"""dropping of unique constraint on room_number

Revision ID: 1d1734e3ba50
Revises: 15d4c68017d8
Create Date: 2025-11-04 16:46:09.030491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1734e3ba50'
down_revision: Union[str, None] = '15d4c68017d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rooms_room_number'), 'rooms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_rooms_room_number'), 'rooms', ['room_number'])
    # ### end Alembic commands ###
