"""Inclusion of Inspection model

Revision ID: 1edcea42dd89
Revises: c2c7a1cf0109
Create Date: 2025-08-22 09:35:38.353426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edcea42dd89'
down_revision: Union[str, None] = 'c2c7a1cf0109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('price', sa.Numeric(), nullable=False))
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.drop_column('properties', 'country')
    op.drop_column('properties', 'amount')
    op.drop_column('properties', 'address')
    op.add_column('transient_verification_store', sa.Column('reason', sa.Enum('email_verification', 'password_change', 'verified', name='email_management_reason_choice'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transient_verification_store', 'reason')
    op.add_column('properties', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_column('properties', 'price')
    # ### end Alembic commands ###
