"""addition of autogenerate=True to the id field of the 'transient_verification_store'

Revision ID: 210cab2dfaff
Revises: 0da79bed1940
Create Date: 2025-10-01 16:59:52.896150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210cab2dfaff'
down_revision: Union[str, None] = '0da79bed1940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
