"""inclusion of users' uid field

Revision ID: 377b2efa825c
Revises: f3bbea4f109b
Create Date: 2025-11-02 02:46:14.457566

"""
import uuid
from sqlalchemy.sql import text
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377b2efa825c'
down_revision: Union[str, None] = 'f3bbea4f109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1 — Add column as nullable
    op.add_column('users', sa.Column('uid', sa.UUID(), nullable=True))

    connection = op.get_bind()

    # Step 2 — Populate all existing users with UUIDs
    results = connection.execute(text("SELECT id FROM users")).fetchall()

    for (user_id,) in results:
        connection.execute(
            text("UPDATE users SET uid = :uid WHERE id = :id"),
            {"uid": str(uuid.uuid4()), "id": user_id},
        )

    # Step 3 — Alter column to be non-nullable
    op.alter_column('users', 'uid', nullable=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
