"""modification of Investment field from amount_invested to investment_amount

Revision ID: 4514c25210d7
Revises: ea9726ec4b0a
Create Date: 2025-03-15 14:28:21.412994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4514c25210d7'
down_revision: Union[str, None] = 'ea9726ec4b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
