"""non-nullability of user_id on BankAccount model

Revision ID: 49d4784ed472
Revises: 1d1734e3ba50
Create Date: 2025-11-04 19:00:58.962119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d4784ed472'
down_revision: Union[str, None] = '1d1734e3ba50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bank_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bank_accounts_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_accounts_pkey')),
    sa.UniqueConstraint('account_number', name=op.f('bank_accounts_account_number_key'))
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    # ### end Alembic commands ###
