"""Addition of guests field to bookings model

Revision ID: 4b8abc342444
Revises: fd7ace1b0462
Create Date: 2025-08-24 19:45:36.970238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8abc342444'
down_revision: Union[str, None] = 'fd7ace1b0462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guests', sa.Integer(), nullable=False))
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'guests')
    # ### end Alembic commands ###
