"""Non-nullification of in transient_verification_store

Revision ID: 69f23b598a03
Revises: 7fc478b9bb34
Create Date: 2025-12-19 06:55:33.920030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f23b598a03'
down_revision: Union[str, None] = '7fc478b9bb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the id column has a proper sequence for auto-increment
    # This fixes any NULL id values by setting a sequence
    op.execute(
        """
        CREATE SEQUENCE IF NOT EXISTS transient_verification_store_id_seq
        AS INTEGER
        START 1
        """
    )
    
    # Update the id column to use the sequence
    op.execute(
        """
        ALTER TABLE transient_verification_store 
        ALTER COLUMN id SET DEFAULT nextval('transient_verification_store_id_seq')
        """
    )
    
    # Ensure all NULL ids are backfilled with sequence values
    op.execute(
        """
        UPDATE transient_verification_store 
        SET id = nextval('transient_verification_store_id_seq') 
        WHERE id IS NULL
        """
    )
    
    # Now ensure id is NOT NULL
    op.alter_column('transient_verification_store', 'id',
               existing_type=sa.Integer(),
               nullable=False,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore id column to allow NULL
    op.alter_column('transient_verification_store', 'id',
               existing_type=sa.Integer(),
               nullable=True,
               existing_nullable=False)
    
    # Remove the sequence default
    op.execute(
        """
        ALTER TABLE transient_verification_store 
        ALTER COLUMN id DROP DEFAULT
        """
    )
    
    # Drop the sequence
    op.execute("DROP SEQUENCE IF EXISTS transient_verification_store_id_seq")
    # ### end Alembic commands ###
