"""Addition of Bank account model

Revision ID: 6f0254a0a809
Revises: 8c7d1e469a5b
Create Date: 2026-01-16 11:01:40.346810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0254a0a809'
down_revision: Union[str, None] = '8c7d1e469a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bank_accounts_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_foreign_key('fk_ratings_room_id', 'ratings', 'rooms', ['room_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_ratings_property_id', 'ratings', 'properties', ['property_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_ratings_hotel_id', 'ratings', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ratings_hotel_id', 'ratings', type_='foreignkey')
    op.drop_constraint('fk_ratings_property_id', 'ratings', type_='foreignkey')
    op.drop_constraint('fk_ratings_room_id', 'ratings', type_='foreignkey')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
