"""re-addition of property_id to 'cloud_image_details' table

Revision ID: 7cb47fb94966
Revises: cb50276d9bbd
Create Date: 2025-09-24 22:42:59.406288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb47fb94966'
down_revision: Union[str, None] = 'cb50276d9bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_image_details', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_cloud_image_detials_property_id_properties', 'cloud_image_details', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cloud_image_detials_property_id_properties', 'cloud_image_details', type_='foreignkey')
    op.drop_column('cloud_image_details', 'property_id')
    # ### end Alembic commands ###
