"""addition of RoleBasedToken model

Revision ID: 7fc478b9bb34
Revises: fa93d14ef659
Create Date: 2025-12-18 09:04:16.053975

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM
from alembic import op
import sqlalchemy as sa

from ppgc_backend.alembic.utils import create_enum_if_not_exists, drop_enum_if_unused


# revision identifiers, used by Alembic.
revision: str = '7fc478b9bb34'
down_revision: Union[str, None] = 'fa93d14ef659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_choice_enum = ENUM('admin', 'staff', 'user', name='role_choice_enum', create_type=False)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum_if_not_exists('role_choice_enum', ['admin', 'staff', 'user'])
    
    op.create_table('role_based_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', role_choice_enum, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_role_based_tokens_created_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_based_tokens_email'), 'role_based_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_role_based_tokens_token'), 'role_based_tokens', ['token'], unique=True)
    op.alter_column('activity_logs', 'activity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('fk_daily_savings_user_id_users', 'daily_savings', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_two_factor_auth_log_user_id_user', 'two_factor_auth_log', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_two_factor_auth_log_user_id_user', 'two_factor_auth_log', type_='foreignkey')
    op.drop_constraint('fk_daily_savings_user_id_users', 'daily_savings', type_='foreignkey')
    op.alter_column('activity_logs', 'activity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_role_based_tokens_token'), table_name='role_based_tokens')
    op.drop_index(op.f('ix_role_based_tokens_email'), table_name='role_based_tokens')
    op.drop_table('role_based_tokens')
    drop_enum_if_unused('role_choice_enum')
    # ### end Alembic commands ###
