"""Removal of hotel relationship from Booking to Hotel

Revision ID: 8a6ab19c37f8
Revises: e75cd7ba66e2
Create Date: 2025-08-24 05:59:43.383460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6ab19c37f8'
down_revision: Union[str, None] = 'e75cd7ba66e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bookings_hotels'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'hotel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_bookings_hotels'), 'bookings', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
