"""Addition of rating model

Revision ID: 8c7d1e469a5b
Revises: bc8b0862e2d8
Create Date: 2026-01-16 10:45:23.088492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM
from ppgc_backend.alembic.utils import create_enum_if_not_exists, drop_enum_if_unused

# revision identifiers, used by Alembic.
revision: str = '8c7d1e469a5b'
down_revision: Union[str, None] = 'bc8b0862e2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

rating_type_values = ['hotel', 'room', 'property']
rating_type_enum = ENUM(*rating_type_values, name='rating_type_enum', create_type=False)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum_if_not_exists('rating_type_enum', rating_type_values)
    
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rateable_type', rating_type_enum, nullable=False),
    sa.Column('rateable_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('commenter_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 5', name='check_score_range'),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], name='fk_ratings_commenter_id_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='fk_ratings_hotel_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_ratings_property_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_ratings_room_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_rateable_id'), 'ratings', ['rateable_id'], unique=False)
    op.create_index(op.f('ix_ratings_rateable_type'), 'ratings', ['rateable_type'], unique=False)
    op.create_foreign_key('fk_daily_savings_user_id_users', 'daily_savings', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_properties_cover_image_id_cloud_image_details', 'properties', 'cloud_image_details', ['cover_image_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_two_factor_auth_log_user_id_user', 'two_factor_auth_log', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_two_factor_auth_log_user_id_user', 'two_factor_auth_log', type_='foreignkey')
    op.drop_constraint('fk_properties_cover_image_id_cloud_image_details', 'properties', type_='foreignkey')
    op.drop_constraint('fk_daily_savings_user_id_users', 'daily_savings', type_='foreignkey')
    op.drop_index(op.f('ix_ratings_rateable_type'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_rateable_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')

    drop_enum_if_unused('rating_type_enum')
    # ### end Alembic commands ###
