"""Modification of Investment model

Revision ID: 96a5de5b3f61
Revises: f827d9265617
Create Date: 2025-11-03 16:40:35.770956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a5de5b3f61'
down_revision: Union[str, None] = 'f827d9265617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('trx_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_investments_trx_id_transactions', 'investments', 'transactions', ['trx_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_transactions_investments'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'investment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('investment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_transactions_investments'), 'transactions', 'investments', ['investment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_investments_trx_id_transactions', 'investments', type_='foreignkey')
    op.drop_column('investments', 'trx_id')
    # ### end Alembic commands ###
