"""post initial migration

Revision ID: 9f9067a43bac
Revises: 545d9000ac55
Create Date: 2025-10-04 20:25:03.348081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f9067a43bac'
down_revision: Union[str, None] = '545d9000ac55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

gender_enum = sa.Enum('male', 'female', 'custom', name='client_gender_choice')
user_role_enum = sa.Enum('admin', 'staff', 'user', name='user_role_choice')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_image', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('other_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('total_stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_hotels_areas', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_properties_area_id_areas', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['cloud_image_details.id'], name='fk_properties_cover_image_id_cloud_image_details', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('cloud_image_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('secure_url', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_cloud_image_detials_property_id_properties', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_cloud_image_details_id'), 'cloud_image_details', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(), nullable=False),
    sa.Column('date_of_inspection', sa.Date(), nullable=False),
    sa.Column('time_of_inspection', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='inspection_status_choice'), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_inspections_properties', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='fk_inspections_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('room_type', sa.Enum('single', 'double', 'suite', 'deluxe', 'family', name='roomtype'), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='fk_rooms_hotels', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', 'completed', name='bookingstatus'), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booker_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booker_id'], ['users.id'], name='fk_bookings_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_bookings_rooms', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_column('areas', 'total_stars')
    op.drop_column('areas', 'total_ratings')
    op.add_column('transient_verification_store', sa.Column('reason', sa.Enum('email_verification', 'password_change', 'verified', name='email_management_reason_choice'), nullable=True))
    op.alter_column('transient_verification_store', 'id',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        postgresql_using="id::integer",
    )
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('gender', gender_enum, nullable=True))
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('user_role', user_role_enum, nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'user_role')
    op.drop_column('users', 'gender')
    op.alter_column('transient_verification_store', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('transient_verification_store', 'reason')
    op.add_column('areas', sa.Column('total_ratings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('areas', sa.Column('total_stars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.alter_column(
        'bookings',
        'status',
        type_=sa.String(),
        existing_type=sa.Enum(
            'pending', 'confirmed', 'canceled', 'completed',
            name='bookingstatus'
        ),
        postgresql_using="status::text"
    )
    op.execute("DROP TYPE IF EXISTS bookingstatus;")
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_cloud_image_details_id'), table_name='cloud_image_details')
    op.drop_table('cloud_image_details')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_table('hotels')

    user_role_enum.drop(op.get_bind(), checkfirst=True)
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
