"""De-nullification of manager_id on hotel

Revision ID: a30ff7e5a64c
Revises: 377b2efa825c
Create Date: 2025-11-02 03:00:52.890888

"""
from sqlalchemy.sql import text
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from ppgc_backend.config.settings import SUPER_ADMIN_EMAIL_ADDRESS


# revision identifiers, used by Alembic.
revision: str = 'a30ff7e5a64c'
down_revision: Union[str, None] = '377b2efa825c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_code', sa.String(), nullable=True))

    connection = op.get_bind()

    # Define the admin email address you want to use
    admin_email = SUPER_ADMIN_EMAIL_ADDRESS

    # Try to fetch the admin's ID
    result = connection.execute(
        text("SELECT id FROM users WHERE email = :email"),
        {"email": admin_email},
    ).fetchone()

    if result:
        admin_id = result[0]
    else:
        # If admin doesn't exist, create one temporarily
        connection.execute(
            text("""
                INSERT INTO users (email, password_hash, user_role, is_admin)
                VALUES (:email, 'temporary_hash', 'admin', TRUE)
            """),
            {"email": admin_email},
        )
        admin_id = connection.execute(
            text("SELECT id FROM users WHERE email = :email"),
            {"email": admin_email},
        ).fetchone()[0]

    # Assign the admin as manager for hotels without manager_id
    connection.execute(
        text("UPDATE hotels SET manager_id = :admin_id WHERE manager_id IS NULL"),
        {"admin_id": admin_id},
    )

    # Finally, alter the column to be non-nullable
    op.alter_column(
        'hotels',
        'manager_id',
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_code')
    op.alter_column('hotels', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
