"""Addition of area to Property model

Revision ID: a3104dea2f0e
Revises: 545d9000ac55
Create Date: 2025-07-26 14:22:34.398147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.inspection import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3104dea2f0e'
down_revision: Union[str, None] = '545d9000ac55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('lease_duration', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_features', sa.Boolean(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_properties_area_id_areas', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    
    columns = [col['name'] for col in inspector.get_columns('transient_verification_store')]
    if 'reason' not in columns:
        op.add_column('transient_verification_store', sa.Column('reason', sa.Enum('email_verification', 'password_change', 'verified', name='email_management_reason_choice'), nullable=True))
   
    op.alter_column('transient_verification_store', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::integer")
    
    
    cols = [c['name'] for c in inspector.get_columns('users')]
    if 'gender' not in cols:
        op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'custom', name='client_gender_choice'), nullable=True))
    if 'user_role' not in cols:
        op.add_column('users', sa.Column('user_role', sa.Enum('admin', 'staff', 'user', name='user_role_choice'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    op.drop_column('users', 'gender')
    op.alter_column('transient_verification_store', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('transient_verification_store', 'reason')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
