"""Non-nullability of room cover image

Revision ID: b31e1b7651b5
Revises: bbf8aff64387
Create Date: 2025-11-21 21:01:11.986265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b31e1b7651b5'
down_revision: Union[str, None] = 'bbf8aff64387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 2️⃣ Fix NULL cover_image values with default placeholder
    op.execute("""
        UPDATE rooms
        SET cover_image = '{"secure_url": "https://abc.com", "public_id": "pub123abc"}'::jsonb
        WHERE cover_image IS NULL
        OR cover_image = '{}'::jsonb
        OR cover_image = 'null'::jsonb
        OR cover_image::text = ''
        OR trim(cover_image::text) = '""';
    """)

    op.alter_column('rooms', 'cover_image',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    
    # Add new value to the existing PostgreSQL enum
    op.execute("ALTER TYPE bookingstatus ADD VALUE IF NOT EXISTS 'booked';")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'cover_image',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
