"""Initial migration

Revision ID: bc8b0862e2d8
Revises: 
Create Date: 2026-01-12 19:17:12.843822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM
from ppgc_backend.alembic.utils import create_enum_if_not_exists, drop_enum_if_unused

# revision identifiers, used by Alembic.
revision: str = 'bc8b0862e2d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


email_management_reason_values = [
    'email_verification',
    'password_change',
    'verified',
    'recovery_email_verification',
]
email_management_reason_choice = ENUM(*email_management_reason_values, name='email_management_reason_choice',create_type=False)


two_factor_log_attempt_values = [
    'setup',
    'verify',
    'failed_attempt',
    'disabled',
]
two_factor_log_attempt_type = ENUM(*two_factor_log_attempt_values, name='two_factor_log_attempt_type',create_type=False)

client_gender_values = ['male', 'female', 'custom']
client_gender_choice = ENUM(*client_gender_values, name='client_gender_choice',create_type=False)

user_role_values = ['admin', 'staff', 'user']
user_role_choice = ENUM(*user_role_values, name='user_role_choice',create_type=False)

activity_status_values = ['success', 'failed', 'pending', 'error']
activity_status_choice = ENUM(*activity_status_values, name='activity_status_choice',create_type=False)

inspection_status_values = ['pending', 'confirmed', 'completed', 'cancelled']
inspection_status_choice= ENUM(*inspection_status_values, name='inspection_status_choice',create_type=False)

investment_status_values = ['active', 'completed', 'canceled']
investment_status= ENUM(*inspection_status_values, name='investment_status',create_type=False)

room_type_values = ['single', 'double', 'suite', 'deluxe', 'family']
roomtype = ENUM(*room_type_values, name='roomtype',create_type=False)

room_status_values = ['available', 'occupied', 'maintenance']
roomstatus = ENUM(*room_status_values, name='roomstatus',create_type=False)

booking_status_values = ['pending', 'confirmed', 'canceled', 'completed', 'cancelled', 'booked']
bookingstatus = ENUM(*booking_status_values, name='bookingstatus',create_type=False)

transaction_type_values = ['deposit', 'withdraw']
transaction_type = ENUM(*transaction_type_values, name='transaction_type',create_type=False)

role_choice_values = ['admin', 'staff', 'user']
role_choice_enum = ENUM(*role_choice_values, name='role_choice_enum',create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum_if_not_exists('email_management_reason_choice', email_management_reason_values)
    create_enum_if_not_exists('two_factor_log_attempt_type', two_factor_log_attempt_values)
    create_enum_if_not_exists('client_gender_choice', client_gender_values)
    create_enum_if_not_exists('user_role_choice', user_role_values)
    create_enum_if_not_exists('activity_status_choice', activity_status_values)
    create_enum_if_not_exists('inspection_status_choice', inspection_status_values)
    create_enum_if_not_exists('investment_status', investment_status_values)
    create_enum_if_not_exists('roomtype', room_type_values)
    create_enum_if_not_exists('roomstatus', room_status_values)
    create_enum_if_not_exists('bookingstatus', booking_status_values)
    create_enum_if_not_exists('transaction_type', transaction_type_values)
    create_enum_if_not_exists('role_choice_enum', role_choice_values)

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state_or_province', sa.String(), nullable=False),
    sa.Column('city_or_town', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('building_name_or_suite', sa.String(), nullable=True),
    sa.Column('zip_or_postal_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('daily_savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_daily_savings_user_id_users', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_savings_id'), 'daily_savings', ['id'], unique=False)
    op.create_table('transient_verification_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('email_code', sa.String(length=255), nullable=True),
    sa.Column('email_code_expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_address_verified', sa.Boolean(), nullable=True),
    sa.Column('email_link', sa.String(), nullable=True),
    sa.Column('email_link_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', email_management_reason_choice, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_index(op.f('ix_transient_verification_store_id'), 'transient_verification_store', ['id'], unique=False)
    op.create_table('two_factor_auth_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_type', two_factor_log_attempt_type, nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_two_factor_auth_log_user_id_user', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_auth_log_id'), 'two_factor_auth_log', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('pin_hash', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('other_names', sa.String(), nullable=True),
    sa.Column('gender', client_gender_choice, nullable=True),
    sa.Column('account_status', sa.String(), nullable=True),
    sa.Column('misc', sa.JSON(), nullable=True),
    sa.Column('user_role', user_role_choice, nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_avatar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nin', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('dial_code', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email_notification', sa.Boolean(), nullable=True),
    sa.Column('push_notification', sa.Boolean(), nullable=True),
    sa.Column('pass_code', sa.String(), nullable=True),
    sa.Column('recovery_email', sa.String(), nullable=True),
    sa.Column('recovery_email_verified', sa.Boolean(), nullable=True),
    sa.CheckConstraint('char_length(nin) = 11', name='check_nin_length_11'),
    sa.CheckConstraint('char_length(pass_code) = 4', name='check_pass_code_length_4'),
    sa.CheckConstraint('char_length(phone_number) = 10', name='check_phone_no_length_10'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_recovery_email'), 'users', ['recovery_email'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('status', activity_status_choice, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_activity_logs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_status'), 'activity_logs', ['status'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_image', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('other_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('receptionist_id', sa.Integer(), nullable=True),
    sa.Column('invite_token', sa.String(length=255), nullable=True),
    sa.Column('invite_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('total_stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_hotels_areas', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='fk_hotels_manager_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receptionist_id'], ['users.id'], name='fk_hotels_receptionist_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_properties_area_id_areas', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['cloud_image_details.id'], name='fk_properties_cover_image_id_cloud_image_details', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('access_token_hash', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_sessions_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_based_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', role_choice_enum, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_role_based_tokens_created_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_based_tokens_email'), 'role_based_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_role_based_tokens_token'), 'role_based_tokens', ['token'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trx_type', transaction_type, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('trx_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transactions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trx_id', name='uq_transactions_trx_id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('two_factor_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('backup_codes', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_two_factor_auth_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_auth_id'), 'two_factor_auth', ['id'], unique=False)
    op.create_table('cloud_image_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('secure_url', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_cloud_image_detials_property_id_properties', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_cloud_image_details_id'), 'cloud_image_details', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(), nullable=False),
    sa.Column('date_of_inspection', sa.Date(), nullable=False),
    sa.Column('time_of_inspection', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', inspection_status_choice, nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_inspections_properties', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='fk_inspections_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('status', investment_status, nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trx_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trx_id'], ['transactions.id'], name='fk_investments_trx_id_transactions', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_investments_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type', roomtype, nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', roomstatus, nullable=False),
    sa.Column('cover_image', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('other_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='fk_rooms_hotels', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('balance_payment', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', bookingstatus, nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booker_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('total_number_of_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booker_id'], ['users.id'], name='fk_bookings_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='fk_bookings_hotels', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_bookings_rooms', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index('ix_bookings_room_check_in_check_out', 'bookings', ['room_id', 'check_in', 'check_out'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index('ix_bookings_room_check_in_check_out', table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_cloud_image_details_id'), table_name='cloud_image_details')
    op.drop_table('cloud_image_details')
    op.drop_index(op.f('ix_two_factor_auth_id'), table_name='two_factor_auth')
    op.drop_table('two_factor_auth')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_role_based_tokens_token'), table_name='role_based_tokens')
    op.drop_index(op.f('ix_role_based_tokens_email'), table_name='role_based_tokens')
    op.drop_table('role_based_tokens')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_status'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_recovery_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_two_factor_auth_log_id'), table_name='two_factor_auth_log')
    op.drop_table('two_factor_auth_log')
    op.drop_index(op.f('ix_transient_verification_store_id'), table_name='transient_verification_store')
    op.drop_table('transient_verification_store')
    op.drop_index(op.f('ix_daily_savings_id'), table_name='daily_savings')
    op.drop_table('daily_savings')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')

    drop_enum_if_unused('bookingstatus')
    drop_enum_if_unused('roomstatus')
    drop_enum_if_unused('roomtype')
    drop_enum_if_unused('investment_status')
    drop_enum_if_unused('inspection_status_choice')
    drop_enum_if_unused('activity_status_choice')
    drop_enum_if_unused('user_role_choice')
    drop_enum_if_unused('client_gender_choice')
    drop_enum_if_unused('two_factor_log_attempt_type')
    drop_enum_if_unused('email_management_reason_choice')
    drop_enum_if_unused('transaction_type')
    drop_enum_if_unused('role_choice_enum')
    # ### end Alembic commands ###
