"""removal of property_id from 'cloud_image_details' table

Revision ID: cb50276d9bbd
Revises: decb6ec78dbb
Create Date: 2025-09-24 20:17:52.887873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb50276d9bbd'
down_revision: Union[str, None] = 'decb6ec78dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cloud_image_details_property_id_properties'), 'cloud_image_details', type_='foreignkey')
    op.drop_column('cloud_image_details', 'property_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_image_details', sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_cloud_image_details_property_id_properties'), 'cloud_image_details', 'properties', ['property_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
