"""removal of other_images_id from propertes table

Revision ID: d554d58da22f
Revises: dd726602e683
Create Date: 2025-09-24 19:32:16.741395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd554d58da22f'
down_revision: Union[str, None] = 'dd726602e683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_properties_other_images_id_cloud_image_details'), 'properties', type_='foreignkey')
    op.drop_column('properties', 'other_images_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('other_images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_properties_other_images_id_cloud_image_details'), 'properties', 'cloud_image_details', ['other_images_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
