"""Parity migration

Revision ID: d5b703ddec0e
Revises: 9f9067a43bac
Create Date: 2025-10-11 09:43:05.416770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5b703ddec0e'
down_revision: Union[str, None] = '9f9067a43bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', 'completed', name='bookingstatus'), nullable=False))
    op.add_column('inspections', sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='inspection_status_choice'), nullable=False))
    op.create_foreign_key('fk_properties_cover_image_id_cloud_image_details', 'properties', 'cloud_image_details', ['cover_image_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('rooms', sa.Column('room_type', sa.Enum('single', 'double', 'suite', 'deluxe', 'family', name='roomtype'), nullable=False))
    op.alter_column('users', 'user_role',
               existing_type=postgresql.ENUM('admin', 'staff', 'user', name='user_role_choice'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=postgresql.ENUM('admin', 'staff', 'user', name='user_role_choice'),
               nullable=True)
    op.drop_column('rooms', 'room_type')
    op.drop_constraint('fk_properties_cover_image_id_cloud_image_details', 'properties', type_='foreignkey')
    op.drop_column('inspections', 'status')
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
