"""Addition of cover_image and other_images field to rooms, unique constraint to room number

Revision ID: dcbd84485e96
Revises: de724eb8a407
Create Date: 2025-10-21 16:23:26.341525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcbd84485e96'
down_revision: Union[str, None] = 'de724eb8a407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('cover_image', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('other_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_rooms_room_number', 'rooms', ['room_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rooms_room_number', 'rooms', type_='unique')
    op.drop_column('rooms', 'other_images')
    op.drop_column('rooms', 'cover_image')
    # ### end Alembic commands ###
