"""modification of nullable on other_images_id on Propety model to True

Revision ID: dd726602e683
Revises: 09ec07304e87
Create Date: 2025-09-24 18:53:52.690157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd726602e683'
down_revision: Union[str, None] = '09ec07304e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'other_images_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'other_images_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
