"""Modification of hotels and rooms table

Revision ID: de724eb8a407
Revises: d5b703ddec0e
Create Date: 2025-10-21 15:28:32.354990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de724eb8a407'
down_revision: Union[str, None] = 'd5b703ddec0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the ENUM type
room_status_enum = sa.Enum('available', 'occupied', 'maintenance', name='roomstatus')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('receptionist_id', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('invite_token', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('invite_token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'hotels', ['invite_token'])
    op.create_foreign_key('fk_hotels_receptionist_id', 'hotels', 'users', ['receptionist_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_hotels_manager_id', 'hotels', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.add_column('rooms', sa.Column('room_number', sa.String(length=50), nullable=True))
    op.add_column('rooms', sa.Column('bed_count', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('rooms', sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True))
    
    # 1. Create ENUM type in Postgres
    room_status_enum.create(op.get_bind())
    # 2. Add column using the newly created type
    op.add_column(
        'rooms',
        sa.Column('status', room_status_enum, nullable=False, server_default='available')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'status')
    # Drop ENUM type
    room_status_enum.drop(op.get_bind())
    op.drop_column('rooms', 'amenities')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'bed_count')
    op.drop_column('rooms', 'room_number')
    op.drop_constraint('fk_hotels_manager_id', 'hotels', type_='foreignkey')
    op.drop_constraint('fk_hotels_receptionist_id', 'hotels', type_='foreignkey')
    op.drop_constraint(None, 'hotels', type_='unique')
    op.drop_column('hotels', 'invite_token_expiry')
    op.drop_column('hotels', 'invite_token')
    op.drop_column('hotels', 'receptionist_id')
    op.drop_column('hotels', 'manager_id')
    # ### end Alembic commands ###
