"""addition of property relationship to cloud_image_details table

Revision ID: decb6ec78dbb
Revises: d554d58da22f
Create Date: 2025-09-24 20:05:29.490288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decb6ec78dbb'
down_revision: Union[str, None] = 'd554d58da22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_image_details', sa.Column('property_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_cloud_image_details_property_id_properties', 'cloud_image_details', 'properties', ['property_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cloud_image_details_property_id_properties', 'cloud_image_details', type_='foreignkey')
    op.drop_column('cloud_image_details', 'property_id')
    # ### end Alembic commands ###
