"""modification of User model, Modification of InvestmentTransaction model to Transaction

Revision ID: f3bbea4f109b
Revises: 25c17cdf315f
Create Date: 2025-11-02 02:10:44.038040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3bbea4f109b'
down_revision: Union[str, None] = '25c17cdf315f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

transaction_type_enum = sa.Enum('deposit', 'withdraw', name='transaction_type')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', transaction_type_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], name='fk_transactions_investments', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transactions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_investment_transactions_id'), table_name='investment_transactions')
    op.drop_table('investment_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('investment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], name=op.f('fk_investments_transactions_investments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('investment_transactions_pkey'))
    )
    op.create_index(op.f('ix_investment_transactions_id'), 'investment_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    transaction_type_enum.drop(op.get_bind, checkfirst=True)
    # ### end Alembic commands ###
