"""modification of user_id foreignkey in Investment model, and addition of user relationship to the model, and addition fof the investments relationship field to the User model

Revision ID: f42fdef1a176
Revises: 4514c25210d7
Create Date: 2025-03-15 16:57:36.896590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42fdef1a176'
down_revision: Union[str, None] = '4514c25210d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
