"""Addition of booked value to BookingStatus enums

Revision ID: f53e08ca5be4
Revises: 157d5c6ca2b2
Create Date: 2025-11-21 07:07:33.609839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53e08ca5be4'
down_revision: Union[str, None] = '157d5c6ca2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
