"""Addition of default to dial-code field of users

Revision ID: f70537aaae4e
Revises: 6f0254a0a809
Create Date: 2026-01-23 11:41:57.761780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70537aaae4e'
down_revision: Union[str, None] = '6f0254a0a809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
