"""addition of trx_id unique constraint to transactions table

Revision ID: f827d9265617
Revises: 1021738fe51d
Create Date: 2025-11-03 07:50:18.108885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f827d9265617'
down_revision: Union[str, None] = '1021738fe51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_transactions_trx_id', 'transactions', ['trx_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_trx_id', 'transactions', type_='unique')
    # ### end Alembic commands ###
