"""Creation of AccountDeactivation, ActivityLog, TwoFactorAuth, TwoFacytorAuthLog models, addition of 'recovery-email-verification' to EmailManagementReasonChoice

Revision ID: fa93d14ef659
Revises: b31e1b7651b5
Create Date: 2025-12-16 04:57:20.127092

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM
from alembic import op
import sqlalchemy as sa

from ppgc_backend.alembic.utils import create_enum_if_not_exists, drop_enum_if_unused


# revision identifiers, used by Alembic.
revision: str = 'fa93d14ef659'
down_revision: Union[str, None] = 'b31e1b7651b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

activity_status_choice = ENUM(
    'success', 'failed', 'pending', 'error', 
    name='activity_status_choice',
    create_type=False
)
two_factor_log_attempt_type = ENUM(
    'setup', 'verify', 'failed_attempt', 'disabled', 
    name='two_factor_log_attempt_type',
    create_type=False
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum_if_not_exists('activity_status_choice', ['success', 'failed', 'pending', 'error'])
    create_enum_if_not_exists('two_factor_log_attempt_type', ['setup', 'verify', 'failed_attempt', 'disabled'])
    

    op.create_table('daily_savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_daily_savings_user_id_users', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_savings_id'), 'daily_savings', ['id'], unique=False)
    op.create_table('two_factor_auth_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_type', two_factor_log_attempt_type, nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_two_factor_auth_log_user_id_user', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_auth_log_id'), 'two_factor_auth_log', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('status', activity_status_choice, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_activity_logs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_status'), 'activity_logs', ['status'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('access_token_hash', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_sessions_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('two_factor_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('backup_codes', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_two_factor_auth_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_auth_id'), 'two_factor_auth', ['id'], unique=False)
    op.add_column('users', sa.Column('recovery_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('recovery_email_verified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_recovery_email'), 'users', ['recovery_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_recovery_email'), table_name='users')
    op.drop_column('users', 'recovery_email_verified')
    op.drop_column('users', 'recovery_email')
    op.drop_index(op.f('ix_two_factor_auth_id'), table_name='two_factor_auth')
    op.drop_table('two_factor_auth')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_status'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # drop enum
    drop_enum_if_unused('activity_status_choice')
    op.drop_index(op.f('ix_two_factor_auth_log_id'), table_name='two_factor_auth_log')
    op.drop_table('two_factor_auth_log')
    # drop enum
    drop_enum_if_unused('two_factor_log_attempt_type')
    op.drop_index(op.f('ix_daily_savings_id'), table_name='daily_savings')
    op.drop_table('daily_savings')
    # ### end Alembic commands ###
