"""Conversion of cover_image_urls to cover_image, and other_images_url to other_images, and the cover_image field to JSON

Revision ID: fd7ace1b0462
Revises: 8a6ab19c37f8
Create Date: 2025-08-24 06:17:56.923511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd7ace1b0462'
down_revision: Union[str, None] = '8a6ab19c37f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('cover_image', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('hotels', sa.Column('other_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('hotels', 'other_image_urls')
    op.drop_column('hotels', 'cover_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('cover_image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('hotels', sa.Column('other_image_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'other_images')
    op.drop_column('hotels', 'cover_image')
    # ### end Alembic commands ###
